project:
  type: website
  output-dir: docs

website:
  title: "challenges"
  navbar:
    left:
      - href: index.qmd
        text: About
      - schedule.qmd
      - lectures.qmd
      - practicals.qmd
  repo-url: https://github.com/gerkovink/challenges
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

